### PR TITLE
Mac build fixes

### PR DESCRIPTION
**Pull request by brlcad**
This is a variety of build changes that get compilation working on Mac.

- need c++11
- compilation fixes for mac
- use a more appropriate var for the libdir

### CODE REVIEW

**Comment by drossberg** [comment]
regex and z library: The library variables are REGEX_STATIC_LIBRARIES and ZLIB_STATIC_LIBRARIES. Despite they are called "static", they can contain references to shared libraries as well: First, the script searches for static BRL-CAD versions of these libraries. If there are none, shared system libraries are good to (see https://github.com/drossberg/MOOSE/blob/master/cmake/FindBRLCAD.cmake#L268).

I.e., especially the static versions of regex_brl and z_brl should be found by FindBRLCAD.cmake. If there are shared versions only, it's a problem (of the BRL-CAD build?)

The brlcad library shall contain all BRL-CAD stuff, dependencies to system libraries or other packages are okay.

**Comment by brlcad** [comment]
I can double check, but I believe the variables are set, but still resulted in an error.  They weren’t specified as link libraries, so it results in unresolved symbols.  It was a default compilation and install of the base brlcad repo.

**Comment by brlcad** [comment]
Oh I see, we’re you implying the commit should use the vars instead of being simply listed?

**Comment by drossberg** [comment]
If REGEX_STATIC_LIBRARIES and ZLIB_STATIC_LIBRARIES don't contain valid libraries, something went wrong. Unfortunately, I can't find out what. The support for the OS on the Mac in my office ended many years ago (it runs now with Windows) and I think mine was the only one my company bought. Hardcoding regex_brl and z_brl is not an option, because this are the wrong libraries for Windows and Linux.

**Comment by brlcad** [comment]
Okay, I'll give the vars a try and test that out, paying a bit more attention to what all the vars get set to.

**Pull request merged**
